apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: friend-mysql
  namespace: friend-ns
spec:
  serviceName: friend-mysql
  replicas: 1
  selector:
    matchLabels:
      app: friend-mysql
  template:
    metadata:
      labels:
        app: friend-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_DATABASE
          value: "frienddb"
        - name: MYSQL_USER
          value: "friend_user"
        - name: MYSQL_PASSWORD
          value: "friend123"
---
apiVersion: v1
kind: Service
metadata:
  name: friend-mysql
  namespace: friend-ns
spec:
  selector:
    app: friend-mysql
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
