name: Deploy to GKE Cluster

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3️⃣ Connect to GKE cluster
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: hello-devops-cluster
          location: asia-northeast1
          project_id: hellodevops-476816

      # 4️⃣ Apply Kubernetes manifests
      - name: Apply Kubernetes manifests
        run: |
          echo "🚀 Deploying to GKE..."
          kubectl apply -f k8s/
          kubectl get pods
          kubectl get svc
          echo "✅ Deployment applied successfully"
